services:   
  tensorflow-serving:
    image: bitnami/tensorflow-serving:2.18.0
    ports:
      - 8500:8500  # Порт для gRPC сервера
      - 8501:8501  # Порт для REST API
    volumes:
      - ../models:/models  # Локальная папка с моделями монтируется в контейнер
    environment:
      - MODEL_NAME=lighttestmodel
    command: >
      tensorflow_model_server
      --model_config_file=/models/models.config   
      --rest_api_port=8501
      --grpc_port=8500
    #cpus: "2.0"         # Ограничение CPU до 2 виртуальных процессоров
    #mem_limit: "4g"     # Ограничение памяти до 4 ГБ